=== myneni/AnimalRest/AnimalSearchRest/src/main/resources/AnimalRequest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="animals">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="animals" maxOccurs="3" minOccurs="3">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:int" name="id"/>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="region"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== myneni/AnimalRest/AnimalSearchRest/src/main/resources/AnimalRequest.xml
<?xml version="1.0" encoding="UTF-8"?>
<animals xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AnimalRequest.xsd">
  <animals>
    <id>0</id>
    <name>name</name>
    <region>region</region>
  </animals>
  <animals>
    <id>0</id>
    <name>name</name>
    <region>region</region>
  </animals>
  <animals>
    <id>0</id>
    <name>name</name>
    <region>region</region>
  </animals>
</animals>
